### ISSUE TITLE
Can't access outside package

### ISSUE THREAD

**Issue by Guilherme-HRamos** [kishan2612/Material-DropView-Android#1]
Hey man, how are you?

I'm testing your lib here, and 

```
backdropContainer.showBackview();
backdropContainer.closeBackview();
```

can't be accessed outside from package :/  can you help me?

*obs: you need to share this lib to community (android arsenal, uplabs...)

Thanks

**Comment by kishan2612** [comment]
Hi @Guilherme-HRamos  issue fixed. Please check the v1.1.0
